/**
 * Blog Configuration
 *
 * Edit this file to customize your blog.
 * Generated by `pnpm blog:setup`. Edit freely — setup won't overwrite this file.
 */
const config = {
  // ─── Site ──────────────────────────────────────────────────────────
  title: "KyoungJin Roh's Blog",
  description: '생각 정리 및 기록',
  locale: 'ko',
  siteUrl: 'https://kyoung-jnn.com',
  siteLogo: 'https://kyoung-jnn.com/icon.ico',
  siteBanner: 'https://kyoung-jnn.com/banner.png',

  // ─── Author ────────────────────────────────────────────────────────
  author: {
    localeName: '노경진',
    enName: 'KyoungJin Roh',
    bio: 'Frontend Engineer',
    contacts: {
      email: 'rudwls468@gmail.com',
      github: 'https://github.com/kyoung-jnn',
      linkedin: 'https://www.linkedin.com/in/%EA%B2%BD%EC%A7%84-%EB%85%B8-028b7421b/',
      twitter: '',
      rss: 'https://kyoung-jnn.com/rss.xml',
    },
  },

  // ─── Comments (https://giscus.app) ─────────────────────────────────
  giscus: {
    repo: 'kyoung-jnn/blog',
    repoId: 'R_kgDOSRb1-Q',
    category: 'Comments',
    categoryId: 'DIC_kwDOSRb1-c4C8Gx-',
  },

  // ─── Navigation ────────────────────────────────────────────────────
  navigation: [
    {
      href: '/article/list/1',
      name: 'articles • 글',
      description: '개발 및 이것저것 포스팅',
    },
    {
      href: '/gallery',
      name: 'gallery • 사진',
      description: '일상 및 여행 사진',
    },
  ],
};

export default config;
